version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M

  flask:
    container_name: flask
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    restart: on-failure:15
    volumes:
      - ./backend/:/app
    depends_on:
      mongodb:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 20s

  nginx:
    container_name: nginx
    restart: on-failure:15
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./nginx/sites-enabled/python-api.conf:/etc/nginx/sites-enabled/python-api.conf
    ports:
      - 80:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 500M
    depends_on:
      flask:
        condition: service_started

volumes:
  mongodb: